---
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create an EC2 instance
    ec2:
      key_name: test 
      region: us-east-1
      group_id: sg-b4989dca
      instance_type: t2.micro
      vpc_subnet_id: subnet-36bb8353
      count: 1
      image: ami-011b3ccf1bd6db744
      assign_public_ip: yes
      wait: yes
      instance_tags:
        Name: RedHat 
        Project: Data Fabric 
        Env: Demo 
    register: ec2
